### PR TITLE
fixed to save confirmation_code even when resend action

### PR DESCRIPTION
**Pull request by kichon**
Hello
I fixed it because the confirmation_code was not saved at the time of resend action

Please confirm it is

### CODE REVIEW

**Comment by bestmomo** [comment]
Hello,
What is the point of creating a code that has already been created during registration?

**Comment by kichon** [comment]
@bestmomo 
thank you for reply.

My point is the fix when installed laravel-email-confirmation after users is already created.

I installed laravel-email-confirmation after user creation.
so, my site user who did resent action dosen't have confirmation_code.

Certainly as you are saying, users who have been created after installed laravel-email-confirmation
had confirmation_code.

if you don't need, i close this pull req.

**Comment by bestmomo** [comment]
Ok I understand, but add a condition to check if **confirmation_code** is empty to avoid useless base update.

**Comment by kichon** [comment]
@bestmomo 
thank you!

I changed it to check condition

**Pull request merged**
